import React from 'react';

export const CyberSecurityPolicyContent: React.FC = () => {
  return (
    <div className="text-slate-300 leading-relaxed space-y-4">
      <h2 className="text-2xl font-semibold text-slate-100 mb-1">Our Commitment to Your Website Security</h2>
      {/* <p className="text-sm text-slate-400 mb-4">Last Updated: [Date]</p> */}

      <p>
        At MajestikMagik.com, we understand that the security of your website is paramount. Just like a well-crafted spell requires careful protection, your online presence deserves robust defenses against the ever-evolving landscape of cyber threats. We want to assure you that we are committed to employing diligent practices and technologies to safeguard your website and the information it holds.
      </p>

      <div className="space-y-2">
        <h3 className="text-xl font-semibold text-slate-200 mt-5 mb-1">Our Proactive Security Measures</h3>
        <p>Here's a glimpse into our ongoing efforts to protect your digital realm from various cyber threats:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li><strong>Protection Against SQL Injection Attacks:</strong> We implement secure coding practices and input validation techniques to prevent malicious SQL queries from being injected into our databases, safeguarding your website's data integrity.</li>
          <li><strong>Defense Against Cross-Site Scripting (XSS) Attacks:</strong> We employ measures to sanitize user input and encode output to prevent attackers from injecting malicious scripts into your website, protecting your visitors from potential harm.</li>
          <li><strong>Regular Security Assessments:</strong> We conduct periodic reviews and assessments of our systems and infrastructure to identify potential vulnerabilities, including those that could be exploited by common attack vectors. This proactive approach allows us to address weaknesses before they can be exploited.</li>
          <li><strong>Industry-Standard Encryption:</strong> We utilize robust encryption methods (like HTTPS/TLS) to protect sensitive data transmitted between your website visitors and our servers, ensuring the confidentiality and integrity of information during transit.</li>
          <li><strong>Firewall Protection:</strong> Our systems are fortified with firewalls that act as barriers against unauthorized access, helping to prevent malicious traffic and attempts to exploit known vulnerabilities.</li>
          <li><strong>Malware Scanning and Prevention:</strong> We implement measures to detect and prevent the introduction of malicious software that could compromise your website's functionality or security.</li>
          <li><strong>Secure Hosting Environment:</strong> We partner with reputable hosting providers that maintain stringent security protocols and physical safeguards, contributing to a more resilient infrastructure.</li>
          <li><strong>Regular Software Updates and Patching:</strong> We diligently keep our software and systems up-to-date with the latest security patches to address known vulnerabilities that attackers might try to exploit.</li>
          <li><strong>Access Controls:</strong> We implement strict access controls to limit who can access sensitive areas of our systems, minimizing the risk of unauthorized modifications or data breaches.</li>
          <li><strong>Data Backup and Recovery:</strong> We maintain regular backups of critical data to ensure business continuity and the ability to recover information in the event of an unforeseen incident, including successful cyber attacks.</li>
          <li><strong>Continuous Monitoring:</strong> Our systems are continuously monitored for suspicious activity and potential indicators of compromise, allowing us to respond promptly to potential security events.</li>
        </ul>
      </div>

      <div className="space-y-2">
        <h3 className="text-xl font-semibold text-slate-200 mt-5 mb-1">Your Role in Maintaining Security</h3>
        <p>While we are dedicated to providing a secure environment, website security is a shared responsibility. We encourage you to:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li><strong>Utilize Two-Factor Authentication (2FA) if available:</strong> Think of 2FA as an extra layer of security for your account. After entering your password, you\'ll be required to provide a second verification factor, typically a code sent to your phone or generated by an authenticator app. This significantly reduces the risk of unauthorized access, even if your password is compromised.</li>
          <li><strong>Regularly Update Your Password:</strong> It's important to change your password periodically to prevent unauthorized access to your account.</li>
          <li><strong>Consider No Password Email-Only Authentication (if offered):</strong> If your website supports email-only authentication, consider using it to provide an additional layer of security. This method streamlines login by eliminating the need for a traditional password. Instead, you\'ll enter your email address, and a unique, temporary link or code will be sent to your inbox to grant access. This removes password-related vulnerabilities, though the security of your email account becomes paramount.</li>
          <li>Use strong, unique passwords for your account and any administrative access to your website.</li>
          <li>Keep your own devices and software updated with the latest security patches and data backups.</li>
          <li>Be cautious of suspicious emails, links, and attachments that could be phishing attempts or vectors for malware.</li>
          <li>Educate yourself and your team on basic cybersecurity best practices to minimize the risk of human error leading to security breaches.</li>
        </ul>
      </div>

      <div className="space-y-2">
        <h3 className="text-xl font-semibold text-slate-200 mt-5 mb-1">Our Ongoing Commitment</h3>
        <p>
          The digital landscape is constantly changing, and so too are the tactics employed by cyber attackers. We are committed to staying informed about the latest security threats and adapting our practices accordingly. Our goal is to provide you with a reliable and secure platform for your online endeavors.
        </p>
        <p>
          By entrusting your website to MajestikMagik.com, you can be confident that we take its security seriously. We are dedicated to maintaining a secure environment where your online presence can thrive.
        </p>
      </div>

      <p className="mt-4">If you have any questions or concerns about our security practices, please do not hesitate to contact us.</p>
    </div>
  );
};