substitutions:
  _FRONTEND_REGION: us-central1
  _BACKEND_REGION: us-east4
  _REPO: majestikmagikcom
  _FRONTEND_SERVICE: majestikmagikcom
  _BACKEND_SERVICE: majestikmagik-api
  _NEWSLETTER_API_URL: https://newsletter-api-845744218342.us-east4.run.app

steps:
  - name: gcr.io/cloud-builders/docker
    dir: .
    args:
      - build
      - -t
      - ${_FRONTEND_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_FRONTEND_SERVICE}:$COMMIT_SHA
      - -f
      - Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    dir: backend
    args:
      - build
      - -t
      - ${_BACKEND_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BACKEND_SERVICE}:$COMMIT_SHA
      - -f
      - Dockerfile
      - .

images:
  - ${_FRONTEND_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_FRONTEND_SERVICE}:$COMMIT_SHA
  - ${_BACKEND_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_BACKEND_SERVICE}:$COMMIT_SHA
